version: "3"
services:
  app:
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3001"
  mongodb:
    image: mongo
    volumes:
      - ./:/usr/src/app
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: "if mongo --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'; then exit 0; fi; exit 1;"
      interval: 60s
      timeout: 15s
      retries: 5
    command: mongod
  mongo_seed:
    image: mongo
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./:/usr/src/app
    command: bash -c 'mongo --host "mongodb" blog --eval "db.projects.drop()" && mongoimport --host "mongodb" -d blog -c projects --file /usr/src/app/app/js/projects/projects.json --jsonArray && mongo --host "mongodb" blog --eval "db.posts.drop()" && mongoimport  --host "mongodb" -d blog -c posts --file /usr/src/app/app/js/blog/posts.json --jsonArray && mongo --host "mongodb" blog --eval "db.gallery.drop()" && mongoimport  --host "mongodb" -d blog -c gallery --file /usr/src/app/app/js/gallery/pix.json --jsonArray'